version: "3.8"
services:
  app:
    build: .
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testinfourhours
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: